/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PPG1.c
**     Project     : Teleskopv3
**     Processor   : MKL46Z256VLL4
**     Component   : PPG_LDD
**     Version     : Component 01.015, Driver 01.03, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-21, 13:27, # CodeGen: 5
**     Abstract    :
**          This component implements a programmable pulse generator that
**          generates signal with variable duty and variable cycle (period).
**     Settings    :
**          Component name                                 : PPG1
**          Module name                                    : TPM2
**          Counter                                        : TPM2_CNT
**          Period device                                  : TPM2_MOD
**          Duty device                                    : TPM2_C0V
**          Output pin                                     : LCD_P2/ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0
**          Output pin signal                              : 
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_TPM2
**            Interrupt priority                           : maximal priority
**            Iterations before action/event               : 1
**          Period                                         : 100 ms
**          Starting pulse width                           : 25 ms
**          Initial polarity                               : low
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnEnd                                      : Enabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init         - LDD_TDeviceData* PPG1_Init(LDD_TUserData *UserDataPtr);
**         Enable       - LDD_TError PPG1_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable      - LDD_TError PPG1_Disable(LDD_TDeviceData *DeviceDataPtr);
**         SetEventMask - LDD_TError PPG1_SetEventMask(LDD_TDeviceData *DeviceDataPtr, LDD_TEventMask...
**         SelectPeriod - LDD_TError PPG1_SelectPeriod(LDD_TDeviceData *DeviceDataPtr, PPG1_TClockList...
**         SetRatio16   - LDD_TError PPG1_SetRatio16(LDD_TDeviceData *DeviceDataPtr, uint16_t Ratio);
**         SetDutyMS    - LDD_TError PPG1_SetDutyMS(LDD_TDeviceData *DeviceDataPtr, uint16_t Time);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PPG1.c
** @version 01.03
** @brief
**          This component implements a programmable pulse generator that
**          generates signal with variable duty and variable cycle (period).
*/         
/*!
**  @addtogroup PPG1_module PPG1 module documentation
**  @{
*/         

/* MODULE PPG1. */

#include "Events.h"
#include "PPG1.h"
#include "FreeRTOS.h" /* FreeRTOS interface */

#ifdef __cplusplus
extern "C" {
#endif 

/* Table of prescaler values for Clock configuration 0 */
static const uint16_t Presc0[PPG1_PERIOD_COUNT] = {
  TPM_PDD_DIVIDE_32,
  TPM_PDD_DIVIDE_16,
  TPM_PDD_DIVIDE_16,
  TPM_PDD_DIVIDE_8,
  TPM_PDD_DIVIDE_2,
  TPM_PDD_DIVIDE_1,
  TPM_PDD_DIVIDE_1,
  TPM_PDD_DIVIDE_1,
  TPM_PDD_DIVIDE_1,
  TPM_PDD_DIVIDE_1,
  TPM_PDD_DIVIDE_2,
  TPM_PDD_DIVIDE_4,
  TPM_PDD_DIVIDE_4,
  TPM_PDD_DIVIDE_4,
  TPM_PDD_DIVIDE_4,
  TPM_PDD_DIVIDE_4
};

typedef struct {
  bool EnUser;                         /* Enable/Disable device */
  bool EnMode;                         /* Enable/Disable device in clock configuration */
  LDD_TEventMask EnEvents;             /* Enable/Disable events mask */
  PPG1_TClockList Selected;            /* Number of actual selected period */
  uint16_t CmpDuty0;                   /* Duty register value for Clock configuration 0 */
  uint16_t CmpPeriod0;                 /* Period register value for Clock configuration 0 */
  uint16_t RatioStore;                 /* Ratio of L-level to H-level */
  uint32_t Source;                     /* Current source clock */
  LDD_TUserData *UserDataPtr;          /* RTOS device data structure */
} PPG1_TDeviceData;

typedef PPG1_TDeviceData *PPG1_TDeviceDataPtr; /* Pointer to the device data structure. */

/* {FreeRTOS RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static PPG1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {FreeRTOS RTOS Adapter} Global variable used for passing a parameter into ISR */
static PPG1_TDeviceDataPtr INT_TPM2__BAREBOARD_RTOS_ISRPARAM;

#define AVAILABLE_EVENTS_MASK (LDD_TEventMask)(LDD_PPG_ON_END)
#define AVAILABLE_PIN_MASK (LDD_TPinMask)(PPG1_OUT_PIN)
#define LAST_PERIOD PPG1_SP_12ms

/* Internal method prototypes */
static void HWEnDi(LDD_TDeviceData *DeviceDataPtr);
static void SetRatio(LDD_TDeviceData *DeviceDataPtr);
/*
** ===================================================================
**     Method      :  PPG1_Init (component PPG_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* PPG1_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate device structure */
  PPG1_TDeviceData *DeviceDataPrv;
  /* {FreeRTOS RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  DeviceDataPrv->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  /* Interrupt vector(s) allocation */
  /* {FreeRTOS RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_TPM2__BAREBOARD_RTOS_ISRPARAM = DeviceDataPrv;
  /* SIM_SCGC6: TPM2=1 */
  SIM_SCGC6 |= SIM_SCGC6_TPM2_MASK;
  /* TPM2_SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DMA=0,TOF=0,TOIE=0,CPWMS=0,CMOD=0,PS=0 */
  TPM2_SC = (TPM_SC_CMOD(0x00) | TPM_SC_PS(0x00)); /* Clear status and control register */
  /* TPM2_CNT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COUNT=0 */
  TPM2_CNT = TPM_CNT_COUNT(0x00);      /* Reset counter register */
  /* TPM2_C0SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CHF=0,CHIE=0,MSB=0,MSA=0,ELSB=0,ELSA=0,??=0,DMA=0 */
  TPM2_C0SC = 0x00U;                   /* Clear channel status and control register */
  /* TPM2_C1SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CHF=0,CHIE=0,MSB=0,MSA=0,ELSB=0,ELSA=0,??=0,DMA=0 */
  TPM2_C1SC = 0x00U;                   /* Clear channel status and control register */
  /* TPM2_MOD: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MOD=0xFFFF */
  TPM2_MOD = TPM_MOD_MOD(0xFFFF);      /* Set up modulo register */
  /* TPM2_C0SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CHF=0,CHIE=0,MSB=1,MSA=0,ELSB=1,ELSA=1,??=0,DMA=0 */
  TPM2_C0SC = (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSB_MASK | TPM_CnSC_ELSA_MASK); /* Set up channel status and control register */
  /* TPM2_C0V: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,VAL=0x4000 */
  TPM2_C0V = TPM_CnV_VAL(0x4000);      /* Set up channel value register */
  /* PORTB_PCR2: ISF=0,MUX=3 */
  PORTB_PCR2 = (uint32_t)((PORTB_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x04)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x03)
               ));
  DeviceDataPrv->EnEvents = 0x01U;     /* Enable selected events */
  DeviceDataPrv->RatioStore = 0x4000U; /* Ratio after initialization */
  DeviceDataPrv->Selected = PPG1_SP_100ms; /* Initial mode identifier */
  DeviceDataPrv->CmpDuty0 = 0x4000U;   /* Duty - duty register value for Clock configuration 0 */
  DeviceDataPrv->CmpPeriod0 = 0xFFFFU; /* Period - period register value for Clock configuration 0 */
  DeviceDataPrv->EnUser = TRUE;        /* Set the flag "device enabled" */
  DeviceDataPrv->Source = TPM_PDD_SYSTEM; /* Store clock source */
  /* NVIC_IPR4: PRI_19=0 */
  NVIC_IPR4 &= (uint32_t)~(uint32_t)(NVIC_IP_PRI_19(0xFF));
  /* NVIC_ISER: SETENA|=0x00080000 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x00080000);
  /* TPM2_SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DMA=0,TOF=0,TOIE=1,CPWMS=0,CMOD=0,PS=0 */
  TPM2_SC = (TPM_SC_TOIE_MASK | TPM_SC_CMOD(0x00) | TPM_SC_PS(0x00)); /* Set up status and control register */
  PPG1_SetClockConfiguration(DeviceDataPrv, Cpu_GetClockConfiguration()); /* Set Initial according clock configuration */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_PPG1_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv); /* Return pointer to the device data structure */
}

/*
** ===================================================================
**     Method      :  PPG1_Enable (component PPG_LDD)
*/
/*!
**     @brief
**         Enables the component - it starts the signal generation.
**         Events may be generated (see SetEventMask).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError PPG1_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!DeviceDataPrv->EnUser) {        /* Is the device disabled by user? */
    DeviceDataPrv->EnUser = TRUE;      /* If yes then set the flag "device enabled" */
    HWEnDi(DeviceDataPtr);             /* Enable/disable device according to status flags */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PPG1_Disable (component PPG_LDD)
*/
/*!
**     @brief
**         Disables the component - it stops signal generation and
**         events calling.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError PPG1_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (DeviceDataPrv->EnUser) {         /* Is the device enabled by user? */
    DeviceDataPrv->EnUser = FALSE;     /* If yes then set the flag "device disabled" */
    HWEnDi(DeviceDataPtr);             /* Enable/disable device according to status flags */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PPG1_SetEventMask (component PPG_LDD)
*/
/*!
**     @brief
**         Enables/disables event(s). The events contained within the
**         mask are enabled. Events not contained within the mask are
**         disabled. The component event masks are defined in the
**         PE_Types.h file. Note: Event that are not generated (See the
**         "Events" tab in the Component inspector) are not handled by
**         this method. In this case the method returns ERR_PARAM_MASK
**         error code. See also method [GetEventMask].
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         EventMask       - Event mask
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_PARAM_MASK - Event mask is not valid
*/
/* ===================================================================*/
LDD_TError PPG1_SetEventMask(LDD_TDeviceData *DeviceDataPtr, LDD_TEventMask EventMask)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  /* Event mask test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((EventMask & ((LDD_TEventMask)~AVAILABLE_EVENTS_MASK)) != 0U) {
    return ERR_PARAM_MASK;
  }
  if ((EventMask & LDD_PPG_ON_END) != 0U) { /* Is the event enabled? */
    TPM_PDD_ClearOverflowInterruptFlag(TPM2_BASE_PTR); /* If yes then clear interrupt request flag */
    TPM_PDD_EnableOverflowInterrupt(TPM2_BASE_PTR); /* and enable overflow interrupt */
  }
  else {
    TPM_PDD_DisableOverflowInterrupt(TPM2_BASE_PTR); /* Disable overflow interrupt */
  }
  DeviceDataPrv->EnEvents = EventMask;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PPG1_SelectPeriod (component PPG_LDD)
*/
/*!
**     @brief
**         Sets new period (setting prescaler a clock source, not an
**         external source such as pin). Up to 16 different values can
**         be predefined in designed-time. This method is enabled only
**         if ["Runtime setting type"] property is set to "from list of
**         values" and if a list of possible periods settings is
**         specified at design time. Each of these settings constitutes
**         a _/period/_ and Processor Expert assigns them a _/period
**         identifier/_. The prescaler corresponding to each mode are
**         calculated at design time. Modes can be switched at runtime
**         just by referring to a mode identifier. No run-time
**         calculations are performed, all the calculations are
**         performed at design time. The periods and periods
**         identifiers may be found in the include file *.h.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Period          - New output period as enumeration
**                           value.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_PARAM_VALUE - Invalid parameter Period
*/
/* ===================================================================*/
LDD_TError PPG1_SelectPeriod(LDD_TDeviceData *DeviceDataPtr, PPG1_TClockList Period)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;
  bool TmrRun;                         /* Temporary flag enable/disable */
  /* Table of period values - period register values for Clock configuration 'for_index_0' */
  static const uint16_t Period0[PPG1_PERIOD_COUNT] = {
    0xFFFFU,
    0xFFFFU,
    0x9999U,
    0x9999U,
    0xCCCCU,
    0xF5C2U,
    0x51EBU,
    0x28F5U,
    0x0830U,
    0x0418U,
    0xF5C2U,
    0x8F5BU,
    0xA3D6U,
    0xB851U,
    0xE147U,
    0xF5C2U
  };

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  /* Parameter test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if (Period > LAST_PERIOD) {          /* Is a values of mode identifier out of range? */
    return ERR_PARAM_VALUE;            /* If yes then error */
  }
  TmrRun = DeviceDataPrv->EnUser;      /* Store actual device state */
  if (DeviceDataPrv->EnUser) {         /* Is the device enabled by user? */
    DeviceDataPrv->EnUser = FALSE;     /* If yes then set the flag "device disabled" */
    HWEnDi(DeviceDataPtr);             /* Enable/disable device according to status flags */
  }
  DeviceDataPrv->Selected = Period;    /* Store given mode identifier to the variable Selected */
  DeviceDataPrv->CmpPeriod0 = Period0[Period]; /* Store appropriate value to variable CmpPeriod0 according to the value of mode identifier for Clock configuration 'for_index_0' */
  SetRatio(DeviceDataPtr);             /* Calculate and set up new appropriate values of the duty and period registers */
  TPM_PDD_SetPrescaler(TPM2_BASE_PTR, Presc0[Period]); /* Set prescaler register according to the value of mode identifier if selected Clock configuration is 'for_index_0' */
  if (TmrRun) {                        /* Was the device enabled? */
    DeviceDataPrv->EnUser = TRUE;      /* If yes set flag "device enabled" */
    HWEnDi(DeviceDataPtr);             /* Enable/disable device according to status flags */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PPG1_SetRatio16 (component PPG_LDD)
*/
/*!
**     @brief
**         This method sets a new duty-cycle ratio. Ratio is expressed
**         as a 16-bit unsigned integer number. 0 - FFFF value is
**         proportional to ratio 0 - 100%. The method is available
**         only if it is not selected list of predefined values in
**         [Starting pulse width] property. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Ratio           - Ratio to set. 0 - 65535 value is
**                           proportional to ratio 0 - 100%
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError PPG1_SetRatio16(LDD_TDeviceData *DeviceDataPtr, uint16_t Ratio)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  DeviceDataPrv->RatioStore = Ratio;   /* Store new value of the ratio */
  SetRatio(DeviceDataPtr);             /* Calculate and set up new appropriate values of the duty and period registers */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PPG1_SetDutyMS (component PPG_LDD)
*/
/*!
**     @brief
**         This method sets the new duty value of the output signal.
**         The duty is expressed in milliseconds as a 16-bit unsigned
**         integer number. The method is available only if it is not
**         selected list of predefined values in [Starting pulse width]
**         property.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Time            - Duty to set [in milliseconds]
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_MATH - Overflow during evaluation
**                           ERR_PARAM_RANGE - Parameter out of range
*/
/* ===================================================================*/
LDD_TError PPG1_SetDutyMS(LDD_TDeviceData *DeviceDataPtr, uint16_t Time)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;
  LDD_PPG_Tfloat rtval;                /* Result of multiplication */

  /* Table of period values in ms for Clock configuration 0 */
  static const uint16_t Period0[PPG1_PERIOD_COUNT] = {
    0x64U,
    0x32U,
    0x1EU,
    0x0FU,
    0x05U,
    0x03U,
    0x01U,
    0x01U,
    0x00U,
    0x00U,
    0x06U,
    0x07U,
    0x08U,
    0x09U,
    0x0BU,
    0x0CU
  };
  /* Table of Clock configuration 0 coefficients */
  static const LDD_PPG_Tfloat Const0[PPG1_PERIOD_COUNT] = {
    655.36F,
    1310.72F,
    2184.511111337165F,
    4369.02222267433F,
    13107.150000190733F,
    21845.180556624015F,
    65534.50003433148F,
    131069.00006866296F,
    655407.5034430139F,
    1310190.2142230696F,
    10922.590278312007F,
    9362.32653079019F,
    8192.00781250745F,
    7281.765432119696F,
    5957.785124150368F,
    5461.295139156004F
  };

  /* Clock configuration test - this test can be disabled by setting the "Ignore clock configuration test"
     property to the "yes" value in the "Configuration inspector" */
  if (!DeviceDataPrv->EnMode) {        /* Is the device disabled in the actual clock configuration? */
    return ERR_SPEED;                  /* If yes then error */
  }
  /* Time test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if (Time >= Period0[DeviceDataPrv->Selected]) { /* Is the given value out of range? */
    return ERR_PARAM_RANGE;            /* If yes then error */
  }
  rtval = Time * Const0[DeviceDataPrv->Selected]; /* Multiply given value and appropriate Clock configuration 0 coefficient */
  if (rtval > 0xFFFFUL) {              /* Is the result greater than 65535 ? */
    DeviceDataPrv->RatioStore = 0xFFFFU; /* If yes then use maximal possible value */
  }
  else {
    DeviceDataPrv->RatioStore = (uint16_t)rtval;
  }
  SetRatio(DeviceDataPtr);             /* Calculate and set up new appropriate values of the duty and period registers */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PPG1_SetClockConfiguration (component PPG_LDD)
**
**     Description :
**         This method changes the clock configuration. During a clock 
**         configuration change the component changes it's setting 
**         immediately upon a request.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PPG1_SetClockConfiguration(LDD_TDeviceData *DeviceDataPtr, LDD_TClockConfiguration ClockConfiguration)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData *)DeviceDataPtr;

  TPM_PDD_SelectPrescalerSource(TPM2_BASE_PTR, TPM_PDD_DISABLED); /* Stop clock */
  TPM_PDD_InitializeCounter(TPM2_BASE_PTR); /* Reset counter */
  switch (ClockConfiguration) {
    case CPU_CLOCK_CONFIG_0:
      DeviceDataPrv->EnMode = TRUE;    /* Set the flag "device enabled" in the actual clock configuration */
      DeviceDataPrv->Source = TPM_PDD_SYSTEM; /* Select clock source */
      TPM_PDD_SetPrescaler(TPM2_BASE_PTR, Presc0[DeviceDataPrv->Selected]); /* Set prescaler register according to the value of mode identifier */
      TPM_PDD_WriteChannelValueReg(TPM2_BASE_PTR, TPM_PDD_CHANNEL_0, DeviceDataPrv->CmpDuty0); /* Set the duty register in Clock configuration 'for_index_0' */
      TPM_PDD_WriteModuloReg(TPM2_BASE_PTR, DeviceDataPrv->CmpPeriod0); /* Set the period register in Clock configuration 'for_index_0' */
      break;
    default:
      DeviceDataPrv->EnMode = FALSE;   /* Set the flag "device disabled" in the actual clock configuration */
      break;
  }
  HWEnDi(DeviceDataPtr);               /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  PPG1_Interrupt (component PPG_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(PPG1_Interrupt)
{
  /* {FreeRTOS RTOS Adapter} ISR parameter is passed through the global variable */
  PPG1_TDeviceDataPtr DeviceDataPrv = INT_TPM2__BAREBOARD_RTOS_ISRPARAM;

  TPM_PDD_ClearOverflowInterruptFlag(TPM2_BASE_PTR); /* Reset interrupt request flag */
  PPG1_OnEnd(DeviceDataPrv->UserDataPtr); /* Invoke OnEnd event */
}

/*
** ===================================================================
**     Method      :  HWEnDi (component PPG_LDD)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(LDD_TDeviceData *DeviceDataPtr)
{
  PPG1_TDeviceDataPtr DeviceDataPrv = (PPG1_TDeviceDataPtr)DeviceDataPtr;

  /* {FreeRTOS RTOS Adapter} Critical section begin (RTOS function call is defined by FreeRTOS RTOS Adapter property) */
  EnterCritical();
  if (DeviceDataPrv->EnMode && DeviceDataPrv->EnUser) { /* Enable device? */
    TPM_PDD_SelectPrescalerSource(TPM2_BASE_PTR, DeviceDataPrv->Source);
  }
  else {
    TPM_PDD_SelectPrescalerSource(TPM2_BASE_PTR, TPM_PDD_DISABLED); /* Stop clock */
    TPM_PDD_InitializeCounter(TPM2_BASE_PTR); /* Reset counter */
  }
  /* {FreeRTOS RTOS Adapter} Critical section ends (RTOS function call is defined by FreeRTOS RTOS Adapter property) */
  ExitCritical();
}
/*
** ===================================================================
**     Method      :  SetRatio (component PPG_LDD)
**
**     Description :
**         Calculates and sets new duty ratio. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(LDD_TDeviceData *DeviceDataPtr)
{
  PPG1_TDeviceData *DeviceDataPrv = (PPG1_TDeviceData*)DeviceDataPtr;

  DeviceDataPrv->CmpDuty0 = (uint16_t)(((((uint32_t)DeviceDataPrv->CmpPeriod0 + 1U) * DeviceDataPrv->RatioStore) + 0x8000U) >> 0x10U); /* Calculate new value of duty register according to the given ratio for Clock configuration 'for_index_0' */
  TPM_PDD_WriteChannelValueReg(TPM2_BASE_PTR, TPM_PDD_CHANNEL_0, DeviceDataPrv->CmpDuty0); /* Set the duty register in Clock configuration 'for_index_0' */
  TPM_PDD_WriteModuloReg(TPM2_BASE_PTR, DeviceDataPrv->CmpPeriod0); /* Set the period register in Clock configuration 'for_index_0' */
}

/* END PPG1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
